version: '3.8'

services:           
    dev:
        container_name: main_dev
        image: main-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        ports:            
            - 3000:3000
            - 9229:9229
        env_file:
            - .env
        networks:
            - nesjs-network
        depends_on:
            - postgres
        links: 
            - postgres:postgres
        restart: unless-stopped
        volumes:
            - .:/src/app
            - /src/app/node_modules
        command : npm run start:dev  

    postgres:
        container_name: postgres
        image: postgres:13.4
        env_file:
            - .env                                                            
        restart: always
networks:
    nesjs-network:
